language: python
python:
- '3.5'
before_script:
  - npm install -g gulp
install:
- pip install .
- pip install -r .travis-requirements.txt
- npm install
before_script:
- bower install
- gulp
script: nosetests
notifications:
  slack:
    secure: JAyJidj1nalEoJhp7JL22tabEXn1xBl6MXQOnP6pratbVyz/haWuDh7OQGZxf0kXO1zaKu6k9A4zQZKr0LiKeUT1Xx5kdeP8C9NzZrYtf6IKLw50HhTq7OhnQ9PtdR2DQ+uT1PcudQWNOeq8+0Yu3aTD/nBH626Gp7qQqRhuX3vUYZs1V05mmxbIrND2OtjR69UkIWwnzFzJDsJCbjY5PojPtfQ1lDlXwulkNV66RfJnJYeWf0ndBgCnEff6OXJ993oUcCWHEsQP5HdgR2IEnyuXHzgjiAnc+M6C4Xes/uS1FEOlwVvpkvysx+FvbQl+SEet+9ottakp5P8QjSKG4159L0Po3n2AISfIcZgMSVuCkIF9mHl23vo8Sb0LdoliHSZhbRP05spAioxf0cfBLBa3isMV2Ur7/BhHjc9Tjxs+obLdJmPRzcch1bYWePFDVJySA57nZUR0CdvObl0h+he+ye5z9/MkfRvHN+kUXkOb5tI+CY1n76vjqoVT6AUagA3Vpsn8Q3dQKhd4JmXg70NeEgM9M0Msql2TDCtEVvk47twEQrlQXCOjGU1B/JJ9l98qQdF3YkuS1vSbjXXZnFYHDg0M6vSddmFhVADfflATbM2pU7v7jdBpTbJxL9rz75Lf535Dk0haM1IWeafmnZhrddq5qrj5+qqsFHmA/ww=
